### ISSUE TITLE
Navbar dan Footer belum dijadiin layout

### ISSUE THREAD

**Issue by khairulihsannudin** [yanridwan/TEDxUGM-3.0#2]
Mba, komponen navbar sama footernya belom ke apply ke semua halaman
Bisa dijadiin ke bagian layout.tsx aja ga mba? tapi homepage nya ga ikutan gitu
jadi di page.tsx cuma komponen hompage, terus di layout.tsx isinya navbar sama footer
aku nyoba tapi belum paham gimana munculin modalnya

_Originally posted by @khairulihsannudin in https://github.com/yanridwan/TEDxUGM-3.0/issues/1#issuecomment-1666538913_

**Comment by geloramanalu** [comment]
oh iya bener juga belom dijadiin layout, aku coba dulu yaa san

**Comment by geloramanalu** [comment]
oh lol ternyata PR terbaru mu udah ngesolve 👍
